// <auto-generated />
using System;
using InteractionTrackerServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InteractionTrackerServer.Migrations
{
    [DbContext(typeof(InteractionContext))]
    partial class InteractionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InteractionTrackerServer.Models.AgentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgentData");
                });

            modelBuilder.Entity("InteractionTrackerServer.Models.CallData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CallerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CallData");
                });

            modelBuilder.Entity("InteractionTrackerServer.Models.Interaction", b =>
                {
                    b.Property<string>("CallId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AgentDataId")
                        .HasColumnType("int");

                    b.Property<int?>("CallDataId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerStatus")
                        .HasColumnType("int");

                    b.Property<int?>("DurationId")
                        .HasColumnType("int");

                    b.Property<int>("IssueStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaitingTimeId")
                        .HasColumnType("int");

                    b.HasKey("CallId");

                    b.HasIndex("AgentDataId");

                    b.HasIndex("CallDataId");

                    b.HasIndex("DurationId");

                    b.HasIndex("WaitingTimeId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("InteractionTrackerServer.Models.TimeWithUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TimeWithUnit");
                });

            modelBuilder.Entity("InteractionTrackerServer.Models.Interaction", b =>
                {
                    b.HasOne("InteractionTrackerServer.Models.AgentData", "AgentData")
                        .WithMany()
                        .HasForeignKey("AgentDataId");

                    b.HasOne("InteractionTrackerServer.Models.CallData", "CallData")
                        .WithMany()
                        .HasForeignKey("CallDataId");

                    b.HasOne("InteractionTrackerServer.Models.TimeWithUnit", "Duration")
                        .WithMany()
                        .HasForeignKey("DurationId");

                    b.HasOne("InteractionTrackerServer.Models.TimeWithUnit", "WaitingTime")
                        .WithMany()
                        .HasForeignKey("WaitingTimeId");

                    b.Navigation("AgentData");

                    b.Navigation("CallData");

                    b.Navigation("Duration");

                    b.Navigation("WaitingTime");
                });
#pragma warning restore 612, 618
        }
    }
}
